<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.2.4</Version>
    <Authors>Keith Heard</Authors>
    <Product>Telemetry</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/keryhe/telemetry</PackageProjectUrl>
    <PackageTags>Keryhe Telemetry Api</PackageTags>
    <AssemblyVersion>1.2.4.0</AssemblyVersion>
    <FileVersion>1.2.4.0</FileVersion>
    <Description>Telemetry Api</Description>
    <Copyright>Copyright 2026</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Keryhe.Telemetry.Core\Keryhe.Telemetry.Core.csproj" />
  </ItemGroup>


</Project>
