-- OpenTelemetry ClickHouse telemetry schema -- telemetry schema 4.0.0
-- Supports OTLP logs, metrics, and traces as defined in opentelemetry-proto.
--
-- Produces the SAME LOGICAL telemetry table/column set as PostgreSQL-Telemetry.sql, adapted to
-- ClickHouse's columnar/OLAP model. Schema 4.0.0 is a fresh-install schema: there is no upgrade path
-- from 2.x or 3.x. ClickHouse holds telemetry data only: tenants, API keys, alert rules and
-- retention settings are the control plane, which a ClickHouse deployment runs on PostgreSQL,
-- SQL Server or MySQL (PostgreSQL-ControlPlane.sql and its siblings, ControlPlane:Provider). In short: spans and log_records are
-- laid out for the way they are read (tenant and service lead the sort key, daily partitions),
-- retention drops whole partitions, and there are no rollup tables, views or orphan tracking.
--
-- Differences from the relational providers:
--
--   1. No auto-increment / RETURNING. Surrogate `id` columns of the reference tables are Int64
--      values GENERATED BY THE APPLICATION (see Keryhe.Telemetry.ClickHouse):
--        - resources.id from (tenant_id, resource_hash) -- the table's full ORDER BY key. The hash
--          covers only schema_url + attributes, so two tenants running the same service share one.
--        - instrumentation_scopes.id from scope_hash (scopes carry no tenant, shared on purpose).
--        - metrics.id from (resource_id, scope_id, name, type).
--      spans.id and log_records.id are a monotonic in-process generator: they are only the
--      keyset-paging tiebreak.
--   2. No UNIQUE constraints / ON CONFLICT. The reference tables (resources, scopes, metrics)
--      are ReplacingMergeTree and collapse
--      rows sharing the ORDER BY key at merge time, backed by an in-process cache + per-batch
--      dedup on the write side. spans is a plain MergeTree: a re-delivered span is stored twice
--      and reads tolerate it (schema-simplification decision 7).
--   3. No foreign keys / cascades.
--   4. Attributes are stored as String (JSON text) columns named *_json, matching how the shared
--      Dapper read repositories deserialize them in C#.
--   5. Timestamps *_unix_nano are Int64 (nanoseconds since epoch), as elsewhere.
--   6. Where null carries no meaning the column is non-Nullable with an empty default
--      (parent_span_id, trace_state, status_message, event_name, log trace_id/span_id,
--      service_name); the read repositories map '' back to null.
--
-- Usage:
--   clickhouse-client --database telemetry --multiquery < ClickHouse-Telemetry.sql
--   (or:  schema/apply-schema.sh telemetry clickhouse telemetry)

-- =============================================================================
-- REFERENCE TABLES
-- =============================================================================

-- Resource: the entity producing telemetry. id = deterministic hash of (tenant_id, resource_hash),
-- matching the ORDER BY below. Both parts are required: the hash covers only schema_url +
-- attributes, so two tenants running the same service produce the same hash.
CREATE TABLE IF NOT EXISTS resources
(
    id              Int64,
    tenant_id       Int64,
    resource_hash   String,
    schema_url      Nullable(String),
    created_at      DateTime64(9) DEFAULT now64(9),
    attributes_json Nullable(String),
    -- Extracted from attributes_json's "service.name" at upsert, and copied onto spans,
    -- log_records and metrics so hot reads filter on a column instead of joining here.
    service_name    Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY (tenant_id, resource_hash);

-- Instrumentation scope (library). id = deterministic hash of scope_hash.
CREATE TABLE IF NOT EXISTS instrumentation_scopes
(
    id              Int64,
    name            String,
    version         Nullable(String),
    schema_url      Nullable(String),
    scope_hash      String,
    created_at      DateTime64(9) DEFAULT now64(9),
    attributes_json Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY scope_hash;

-- =============================================================================
-- TRACES
-- =============================================================================

-- Spans: a plain MergeTree laid out for the way spans are read. Every list/summary query is a
-- tenant (and usually service) plus start-time window, so those lead the sort key; the daily
-- partition on start_time_unix_nano makes retention a DROP PARTITION and lets a time window skip
-- whole days. A trace's spans are found through trace_index below, not by sort-key position.
CREATE TABLE IF NOT EXISTS spans
(
    id                       Int64,
    tenant_id                Int64,
    service_name             LowCardinality(String) DEFAULT '',
    trace_id                 String,
    span_id                  String,
    parent_span_id           String DEFAULT '',
    resource_id              Int64,
    scope_id                 Int64,
    name                     LowCardinality(String),
    kind                     LowCardinality(String) DEFAULT 'UNSPECIFIED',
    start_time_unix_nano     Int64,
    end_time_unix_nano       Int64,
    dropped_attributes_count Int32 DEFAULT 0,
    dropped_events_count     Int32 DEFAULT 0,
    dropped_links_count      Int32 DEFAULT 0,
    trace_state              String DEFAULT '',
    flags                    Int32 DEFAULT 0,
    status_code              LowCardinality(String) DEFAULT 'UNSET',
    status_message           String DEFAULT '',
    created_at               DateTime64(9) DEFAULT now64(9),
    attributes_json          Nullable(String),
    events_json              Nullable(String),
    links_json               Nullable(String),
    -- Trace detail (3.0.1). The sort key has no trace-id seek, so a by-trace read -- even bounded by trace_index to the trace's
    -- time -- reads at least one 8192-row granule of every service in that range (about 143,000 rows per call under the stress
    -- harness). This skips the granules whose trace ids cannot match, the same index log_records carries for logs-by-trace.
    INDEX idx_spans_trace trace_id TYPE bloom_filter(0.01) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(start_time_unix_nano))
ORDER BY (tenant_id, service_name, start_time_unix_nano);

-- trace_index: min/max start time per (tenant, trace, day), fed by a materialized view from
-- spans. Trace detail reads it first for the trace's time bounds, then reads spans with tenant
-- and time bounds so only the partitions and granules that can hold the trace are touched. One
-- row per (tenant, trace, day) because the day is the partition key (a trace spanning midnight
-- has two); reads merge them with minMerge/maxMerge.
CREATE TABLE IF NOT EXISTS trace_index
(
    tenant_id Int64,
    trace_id  String,
    day       Date,
    min_start AggregateFunction(min, Int64),
    max_start AggregateFunction(max, Int64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMMDD(day)
ORDER BY (tenant_id, trace_id);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_trace_index
TO trace_index AS
SELECT tenant_id,
       trace_id,
       toDate(fromUnixTimestamp64Nano(start_time_unix_nano)) AS day,
       minState(start_time_unix_nano) AS min_start,
       maxState(start_time_unix_nano) AS max_start
FROM spans
GROUP BY tenant_id, trace_id, day;

-- =============================================================================
-- METRICS
-- =============================================================================

-- Base metrics table. tenant_id and service_name are copied from the resolved resource when the
-- row is first written (cannot go stale: the resource hash includes service.name).
CREATE TABLE IF NOT EXISTS metrics
(
    id           Int64,
    tenant_id    Int64,
    service_name LowCardinality(String) DEFAULT '',
    resource_id  Int64,
    scope_id     Int64,
    name         String,
    description  Nullable(String),
    unit         Nullable(String),
    type         String,
    created_at   DateTime64(9) DEFAULT now64(9)
)
-- Metric identity, the ClickHouse analogue of the relational uk_metric_identity UNIQUE.
-- ORDER BY must equal the dedup key exactly and contain nothing else: `id` is a pure function of
-- the key, and `created_at` varies per insert and would defeat the collapse. Dedup is EVENTUAL
-- (merge time); the write-side cache reduces inserts to one per metric per process lifetime.
ENGINE = ReplacingMergeTree
ORDER BY (resource_id, scope_id, name, type);

-- exemplars_json holds the OTLP exemplar list (every data point except Summary).

CREATE TABLE IF NOT EXISTS gauge_data_points
(
    id                   Int64 DEFAULT 0,
    metric_id            Int64,
    start_time_unix_nano Nullable(Int64),
    time_unix_nano       Int64,
    value_double         Nullable(Float64),
    value_int            Nullable(Int64),
    flags                Int32 DEFAULT 0,
    attributes_json      Nullable(String),
    exemplars_json       Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS sum_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    value_double            Nullable(Float64),
    value_int               Nullable(Int64),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    is_monotonic            UInt8 DEFAULT 0,
    flags                   Int32 DEFAULT 0,
    attributes_json         Nullable(String),
    exemplars_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS histogram_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    count                   Int64,
    sum_value               Nullable(Float64),
    bucket_counts           Nullable(String),
    explicit_bounds         Nullable(String),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    flags                   Int32 DEFAULT 0,
    min_value               Nullable(Float64),
    max_value               Nullable(Float64),
    attributes_json         Nullable(String),
    exemplars_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS exponential_histogram_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    count                   Int64,
    sum_value               Nullable(Float64),
    scale                   Int32,
    zero_count              Int64,
    positive_offset         Nullable(Int32),
    positive_bucket_counts  Nullable(String),
    negative_offset         Nullable(Int32),
    negative_bucket_counts  Nullable(String),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    flags                   Int32 DEFAULT 0,
    min_value               Nullable(Float64),
    max_value               Nullable(Float64),
    attributes_json         Nullable(String),
    exemplars_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS summary_data_points
(
    id                   Int64 DEFAULT 0,
    metric_id            Int64,
    start_time_unix_nano Nullable(Int64),
    time_unix_nano       Int64,
    count                Int64,
    sum_value            Float64,
    quantile_values      Nullable(String),
    flags                Int32 DEFAULT 0,
    attributes_json      Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

-- metric_last_seen: the metrics catalog's "has data in range" check reads this instead of scanning
-- the five data-point tables above. An AggregatingMergeTree holding a partial maxState(time_unix_nano)
-- per metric_id, fed by one materialized view per data-point table below -- not a mutation per flush
-- interval like the relational providers' MetricTouchWorker. Reads merge partial states with
-- maxMerge(last_seen_state). No worker, no mutations.
CREATE TABLE IF NOT EXISTS metric_last_seen
(
    metric_id       Int64,
    last_seen_state AggregateFunction(max, Int64)
)
ENGINE = AggregatingMergeTree
ORDER BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_gauge
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM gauge_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_sum
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM sum_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_histogram
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM histogram_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_exponential_histogram
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM exponential_histogram_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_summary
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM summary_data_points
GROUP BY metric_id;

-- =============================================================================
-- LOGS
-- =============================================================================

-- Log records, laid out like spans: tenant and service lead the sort key, daily partitions,
-- retention is a DROP PARTITION. The bloom_filter skip index on trace_id serves logs-by-trace.
CREATE TABLE IF NOT EXISTS log_records
(
    id                       Int64 DEFAULT 0,
    tenant_id                Int64,
    service_name             LowCardinality(String) DEFAULT '',
    resource_id              Int64,
    scope_id                 Int64,
    time_unix_nano           Int64 DEFAULT 0,
    observed_time_unix_nano  Nullable(Int64),
    severity_number          Nullable(Int32),
    severity_text            LowCardinality(Nullable(String)),
    event_name               String DEFAULT '',
    body_type                Nullable(String),
    body_value               Nullable(String),
    dropped_attributes_count Int32 DEFAULT 0,
    flags                    Int32 DEFAULT 0,
    trace_id                 String DEFAULT '',
    span_id                  String DEFAULT '',
    created_at               DateTime64(9) DEFAULT now64(9),
    attributes_json          Nullable(String),
    INDEX idx_log_trace trace_id TYPE bloom_filter(0.01) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (tenant_id, service_name, time_unix_nano);

-- =============================================================================
-- SUMMARY ROLLUPS (schema 3.2.0; plans/summary-rollups.md)
-- =============================================================================

-- Per-minute rollups the dashboard, trace list and logs page read instead of scanning spans and
-- log records. request_rollup_minute counts INBOUND spans (kind SERVER or CONSUMER) per
-- (tenant, service, minute of start time): request_count, error_count, duration sum/max and a
-- 24-band doubling duration histogram (h00 = under 0.25 ms, hNN = [0.25 ms * 2^(NN-1), 0.25 ms * 2^NN),
-- h23 = 1,048.6 s and over). log_rollup_minute counts log records per (tenant, service, severity
-- number, minute); severity_number is -1 for a record whose severity is NULL. Rows are partial:
-- no unique key, no foreign keys, reads SUM them. service_name is '' for a span or log without one.
-- ClickHouse: AggregatingMergeTree tables fed by materialized views on spans (inbound only) and
-- log_records, so there is no accumulator or worker. Reads use sum()/max() with GROUP BY, never FINAL.
-- The band expression is the integer form of DurationBands.IndexOf: a negative duration counts as 0,
-- under 250,000 ns is h00, otherwise min(23, floor(log2(duration / 250,000)) + 1), via floor(log2(...)).
CREATE TABLE IF NOT EXISTS request_rollup_minute
(
    tenant_id              Int64,
    service_name           LowCardinality(String) DEFAULT '',
    bucket_start_unix_nano Int64,
    request_count          SimpleAggregateFunction(sum, Int64),
    error_count            SimpleAggregateFunction(sum, Int64),
    sum_duration_nanos     SimpleAggregateFunction(sum, Int64),
    max_duration_nanos     SimpleAggregateFunction(max, Int64),
    h00 SimpleAggregateFunction(sum, Int64),
    h01 SimpleAggregateFunction(sum, Int64),
    h02 SimpleAggregateFunction(sum, Int64),
    h03 SimpleAggregateFunction(sum, Int64),
    h04 SimpleAggregateFunction(sum, Int64),
    h05 SimpleAggregateFunction(sum, Int64),
    h06 SimpleAggregateFunction(sum, Int64),
    h07 SimpleAggregateFunction(sum, Int64),
    h08 SimpleAggregateFunction(sum, Int64),
    h09 SimpleAggregateFunction(sum, Int64),
    h10 SimpleAggregateFunction(sum, Int64),
    h11 SimpleAggregateFunction(sum, Int64),
    h12 SimpleAggregateFunction(sum, Int64),
    h13 SimpleAggregateFunction(sum, Int64),
    h14 SimpleAggregateFunction(sum, Int64),
    h15 SimpleAggregateFunction(sum, Int64),
    h16 SimpleAggregateFunction(sum, Int64),
    h17 SimpleAggregateFunction(sum, Int64),
    h18 SimpleAggregateFunction(sum, Int64),
    h19 SimpleAggregateFunction(sum, Int64),
    h20 SimpleAggregateFunction(sum, Int64),
    h21 SimpleAggregateFunction(sum, Int64),
    h22 SimpleAggregateFunction(sum, Int64),
    h23 SimpleAggregateFunction(sum, Int64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(bucket_start_unix_nano))
ORDER BY (tenant_id, bucket_start_unix_nano, service_name);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_request_rollup_minute
TO request_rollup_minute AS
SELECT tenant_id,
       service_name,
       intDiv(start_time_unix_nano, 60000000000) * 60000000000 AS bucket_start_unix_nano,
       count() AS request_count,
       countIf(status_code = 'ERROR') AS error_count,
       sum(dur_ns) AS sum_duration_nanos,
       max(dur_ns) AS max_duration_nanos,
       countIf(band = 0) AS h00,
       countIf(band = 1) AS h01,
       countIf(band = 2) AS h02,
       countIf(band = 3) AS h03,
       countIf(band = 4) AS h04,
       countIf(band = 5) AS h05,
       countIf(band = 6) AS h06,
       countIf(band = 7) AS h07,
       countIf(band = 8) AS h08,
       countIf(band = 9) AS h09,
       countIf(band = 10) AS h10,
       countIf(band = 11) AS h11,
       countIf(band = 12) AS h12,
       countIf(band = 13) AS h13,
       countIf(band = 14) AS h14,
       countIf(band = 15) AS h15,
       countIf(band = 16) AS h16,
       countIf(band = 17) AS h17,
       countIf(band = 18) AS h18,
       countIf(band = 19) AS h19,
       countIf(band = 20) AS h20,
       countIf(band = 21) AS h21,
       countIf(band = 22) AS h22,
       countIf(band = 23) AS h23
FROM
(
    SELECT tenant_id, service_name, start_time_unix_nano, status_code,
           greatest(end_time_unix_nano - start_time_unix_nano, 0) AS dur_ns,
           if(dur_ns < 250000, 0, least(23, toUInt8(floor(log2(intDiv(dur_ns, 250000)))) + 1)) AS band
    FROM spans
    WHERE kind IN ('SERVER', 'CONSUMER')
)
GROUP BY tenant_id, service_name, bucket_start_unix_nano;

CREATE TABLE IF NOT EXISTS log_rollup_minute
(
    tenant_id              Int64,
    service_name           LowCardinality(String) DEFAULT '',
    severity_number        Int32,
    bucket_start_unix_nano Int64,
    record_count           SimpleAggregateFunction(sum, Int64)
)
ENGINE = AggregatingMergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(bucket_start_unix_nano))
ORDER BY (tenant_id, bucket_start_unix_nano, service_name, severity_number);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_log_rollup_minute
TO log_rollup_minute AS
SELECT tenant_id,
       service_name,
       ifNull(severity_number, -1) AS severity_number,
       intDiv(time_unix_nano, 60000000000) * 60000000000 AS bucket_start_unix_nano,
       count() AS record_count
FROM log_records
GROUP BY tenant_id, service_name, severity_number, bucket_start_unix_nano;

-- =============================================================================
-- UTILITY
-- =============================================================================

CREATE TABLE IF NOT EXISTS telemetry_schema_version
(
    version    String,
    applied_at DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree
ORDER BY version;

-- The telemetry_schema_version row is seeded LAST, so a partial/failed apply never records a version that
-- the apply-schema.sh version gate would wrongly treat as "already applied".
INSERT INTO telemetry_schema_version (version) VALUES ('4.0.0');
