-- OpenTelemetry ClickHouse Schema
-- Supports OTLP logs, metrics, and traces as defined in opentelemetry-proto.
--
-- Produces the SAME LOGICAL table/column set as PostgreSQL-Schema.sql, adapted to
-- ClickHouse's columnar/OLAP model. The important differences from the relational
-- providers:
--
--   1. No auto-increment / RETURNING. Surrogate `id` columns are Int64 values
--      GENERATED BY THE APPLICATION (see Keryhe.Telemetry.ClickHouse):
--        - resources.id is derived deterministically from (tenant_id, resource_hash) -- the
--          table's full ORDER BY key. Deriving it from resource_hash alone gave two tenants with
--          identical resources one shared id, which leaked across tenants on read. A database
--          written before that fix must be re-created; there is no in-place migration.
--        - instrumentation_scopes.id is derived from scope_hash, which IS its whole key (scopes
--          carry no tenant and are shared across tenants by design).
--        - spans.id is derived deterministically from (trace_id, span_id).
--        - metrics.id is derived deterministically from (resource_id, scope_id, name, type).
--   2. No UNIQUE constraints / ON CONFLICT. Dedup of resources, scopes, spans, and metrics is
--      handled by ReplacingMergeTree (collapses rows sharing the ORDER BY key at merge
--      time), backed by an in-process cache + per-batch dedup on the write side.
--   3. No foreign keys / cascades. Referential integrity is a write-path convention;
--      deletes remove child rows explicitly (see ClickHouseWriteStore).
--   4. Attributes are stored as String (JSON text) columns named *_json, matching how the
--      shared Dapper read repositories deserialize them in C#.
--   5. Timestamps *_unix_nano are Int64 (nanoseconds since epoch), as elsewhere.
--
-- Usage:
--   clickhouse-client --database telemetry --multiquery < ClickHouse-Schema.sql
--   (or:  schema/apply-schema.sh clickhouse telemetry)

-- =============================================================================
-- COMMON / MULTI-TENANT TABLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS tenants
(
    id         Int64,
    name       String,
    created_at DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree
ORDER BY id;

CREATE TABLE IF NOT EXISTS api_keys
(
    id           Int64,
    tenant_id    Int64,
    key_hash     String,
    name         String,
    is_active    UInt8 DEFAULT 1,
    created_at   DateTime64(9) DEFAULT now64(9),
    last_used_at Nullable(DateTime64(9))
)
ENGINE = ReplacingMergeTree
ORDER BY key_hash;

-- Resource: the entity producing telemetry. id = deterministic hash of (tenant_id, resource_hash),
-- matching the ORDER BY below. Both parts are required: the hash covers only schema_url +
-- attributes, so two tenants running the same service produce the same hash.
CREATE TABLE IF NOT EXISTS resources
(
    id              Int64,
    tenant_id       Int64,
    resource_hash   String,
    schema_url      Nullable(String),
    created_at      DateTime64(9) DEFAULT now64(9),
    attributes_json Nullable(String),
    -- service_name (schema 2.13.3, list-pages-server-side plan Phase 7): a real column, written
    -- by ClickHouseBulkWriter's resource upsert, extracted from attributes_json's
    -- "service.name" key. ResourceServiceNameExpr() is now just "{alias}.service_name".
    service_name    Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY (tenant_id, resource_hash);

-- Instrumentation scope (library). id = deterministic hash of scope_hash.
CREATE TABLE IF NOT EXISTS instrumentation_scopes
(
    id              Int64,
    name            String,
    version         Nullable(String),
    schema_url      Nullable(String),
    scope_hash      String,
    created_at      DateTime64(9) DEFAULT now64(9),
    attributes_json Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY scope_hash;

-- =============================================================================
-- TRACES
-- =============================================================================

-- Spans. Dedup key is (trace_id, span_id); id is derived from that pair.
CREATE TABLE IF NOT EXISTS spans
(
    id                       Int64,
    trace_id                 String,
    span_id                  String,
    parent_span_id           Nullable(String),
    resource_id              Int64,
    scope_id                 Int64,
    name                     String,
    kind                     String DEFAULT 'UNSPECIFIED',
    start_time_unix_nano     Int64,
    end_time_unix_nano       Int64,
    dropped_attributes_count Int32 DEFAULT 0,
    dropped_events_count     Int32 DEFAULT 0,
    dropped_links_count      Int32 DEFAULT 0,
    trace_state              Nullable(String),
    flags                    Int32 DEFAULT 0,
    status_code              String DEFAULT 'UNSET',
    status_message           Nullable(String),
    created_at               DateTime64(9) DEFAULT now64(9),
    attributes_json          Nullable(String),
    events_json              Nullable(String),
    links_json               Nullable(String),
    -- Search skip indexes (schema 2.13.3, list-pages-server-side plan Phase 7, analytics tier --
    -- decision 39). Unlike the relational providers' GIN indexes, these do not change the query
    -- that runs: FreeTextPredicate's `name ILIKE '%text%'`-equivalent and AttributePredicate's
    -- phase-1 JSONExtractRaw predicate stay exactly as they were. A skip index only lets
    -- ClickHouse skip whole granules that cannot match before evaluating the predicate against
    -- what's left -- ngrambf_v1 for substring search on name/status_message, tokenbf_v1 for
    -- attributes_json so a key:value predicate can prune granules that don't contain the
    -- searched token at all. GRANULARITY 4 groups 4 index blocks (index_granularity rows each,
    -- default 8192) per skip-index entry -- the library's existing default, matched here rather
    -- than tuned separately.
    INDEX idx_spans_name_ngram name TYPE ngrambf_v1(3, 4096, 2, 0) GRANULARITY 4,
    INDEX idx_spans_status_message_ngram assumeNotNull(status_message) TYPE ngrambf_v1(3, 4096, 2, 0) GRANULARITY 4,
    INDEX idx_spans_attributes_tokenbf assumeNotNull(attributes_json) TYPE tokenbf_v1(8192, 3, 0) GRANULARITY 4
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(start_time_unix_nano))
ORDER BY (trace_id, span_id);

-- schema 2.12.0 adds idx_spans_error (a status_code-filtered index on start_time_unix_nano) to
-- the other four providers, for mode=errors. Not needed here: the daily partition plus this
-- table's own ORDER BY (trace_id, span_id) already lets a status_code='ERROR' scan skip whole
-- partitions/granules outside the query's time bounds without a dedicated index.

-- span_events and span_links were dropped in 2.11.0: neither was ever read or written
-- independently of its parent span, so both collapsed into spans.events_json/links_json.

-- idx_spans_root_time (schema 2.13.1, list-pages-server-side plan Phase 3) has no ClickHouse
-- equivalent either, for the same reason as idx_spans_error: the daily partition plus this
-- table's own ORDER BY (trace_id, span_id) already lets a parent_span_id IS NULL scan skip
-- whole partitions/granules outside the query's time bounds. Revisit with a projection if
-- EXPLAIN ever shows otherwise.

-- =============================================================================
-- METRICS
-- =============================================================================

CREATE TABLE IF NOT EXISTS metrics
(
    id          Int64,
    resource_id Int64,
    scope_id    Int64,
    name        String,
    description Nullable(String),
    unit        Nullable(String),
    type        String,
    created_at  DateTime64(9) DEFAULT now64(9)
)
-- Metric identity, the ClickHouse analogue of the relational uk_metric_identity UNIQUE.
-- ORDER BY must equal the dedup key exactly and contain nothing else:
--   * `id` is a pure function of the key, so it adds no selectivity -- and including it is
--     precisely why the previous `MergeTree ORDER BY (name, id)` never collapsed anything,
--     since id was a fresh RowId.Next() on every export.
--   * `created_at` must never be added: it varies per insert and would defeat the collapse.
--
-- `name` no longer leads the sort key. That is fine here: dedup takes this table to tens of
-- rows, which is a single 8192-row granule, so every lookup reads the same granule whatever
-- the key order -- and the high-volume reads join on metric_id rather than scanning by name.
--
-- Dedup is EVENTUAL (merge time). The write-side cache reduces inserts to one per metric per
-- process lifetime, so duplicates are only visible in the window just after a restart.
ENGINE = ReplacingMergeTree
ORDER BY (resource_id, scope_id, name, type);

-- exemplars_json (2.9.0) replaces the former single exemplar_id column and the shared
-- `exemplars` table, which no writer ever populated. OTLP declares `repeated Exemplar
-- exemplars` on every data point except Summary, so one id per row could never hold more than
-- the first. The list is stored as JSON on the data point itself: a child table would need each
-- data point's generated id, which the bulk-load path (binary COPY / bulk copy) does not hand
-- back, and JSON is already how bucket_counts, explicit_bounds and quantile_values are stored.
-- Trade-off: an exemplar's trace_id is no longer indexable. No read path queries it.
CREATE TABLE IF NOT EXISTS gauge_data_points
(
    id                   Int64 DEFAULT 0,
    metric_id            Int64,
    start_time_unix_nano Nullable(Int64),
    time_unix_nano       Int64,
    value_double         Nullable(Float64),
    value_int            Nullable(Int64),
    flags                Int32 DEFAULT 0,
    attributes_json      Nullable(String),
    exemplars_json       Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS sum_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    value_double            Nullable(Float64),
    value_int               Nullable(Int64),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    is_monotonic            UInt8 DEFAULT 0,
    flags                   Int32 DEFAULT 0,
    attributes_json         Nullable(String),
    exemplars_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS histogram_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    count                   Int64,
    sum_value               Nullable(Float64),
    bucket_counts           Nullable(String),
    explicit_bounds         Nullable(String),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    flags                   Int32 DEFAULT 0,
    min_value               Nullable(Float64),
    max_value               Nullable(Float64),
    attributes_json         Nullable(String),
    exemplars_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS exponential_histogram_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    count                   Int64,
    sum_value               Nullable(Float64),
    scale                   Int32,
    zero_count              Int64,
    positive_offset         Nullable(Int32),
    positive_bucket_counts  Nullable(String),
    negative_offset         Nullable(Int32),
    negative_bucket_counts  Nullable(String),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    flags                   Int32 DEFAULT 0,
    min_value               Nullable(Float64),
    max_value               Nullable(Float64),
    attributes_json         Nullable(String),
    exemplars_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS summary_data_points
(
    id                   Int64 DEFAULT 0,
    metric_id            Int64,
    start_time_unix_nano Nullable(Int64),
    time_unix_nano       Int64,
    count                Int64,
    sum_value            Float64,
    quantile_values      Nullable(String),
    flags                Int32 DEFAULT 0,
    attributes_json      Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

-- metric_last_seen (schema 2.13.2, list-pages-server-side plan Phase 5, decision 27): the
-- metrics catalog's "has data in range" check reads this instead of scanning the five
-- data-point tables above. An AggregatingMergeTree holding a partial maxState(time_unix_nano)
-- per metric_id, fed by one materialized view per data-point table below -- not a mutation per
-- flush interval like the relational providers' MetricTouchWorker, since `ALTER TABLE ...
-- UPDATE` on every flush would be a continuous stream of heavy mutations on ClickHouse. Reads
-- merge partial states with maxMerge(last_seen_state). No worker, no mutations.
CREATE TABLE IF NOT EXISTS metric_last_seen
(
    metric_id       Int64,
    last_seen_state AggregateFunction(max, Int64)
)
ENGINE = AggregatingMergeTree
ORDER BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_gauge
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM gauge_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_sum
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM sum_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_histogram
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM histogram_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_exponential_histogram
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM exponential_histogram_data_points
GROUP BY metric_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metric_last_seen_summary
TO metric_last_seen AS
SELECT metric_id, maxState(time_unix_nano) AS last_seen_state
FROM summary_data_points
GROUP BY metric_id;

-- =============================================================================
-- LOGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS log_records
(
    id                       Int64 DEFAULT 0,
    resource_id              Int64,
    scope_id                 Int64,
    time_unix_nano           Int64 DEFAULT 0,
    observed_time_unix_nano  Nullable(Int64),
    severity_number          Nullable(Int32),
    severity_text            Nullable(String),
    event_name               Nullable(String),
    body_type                Nullable(String),
    body_value               Nullable(String),
    dropped_attributes_count Int32 DEFAULT 0,
    flags                    Int32 DEFAULT 0,
    trace_id                 Nullable(String),
    span_id                  Nullable(String),
    created_at               DateTime64(9) DEFAULT now64(9),
    attributes_json          Nullable(String),
    -- Search skip indexes (schema 2.13.3, Phase 7, analytics tier) -- see the identical spans
    -- comment above for the ngrambf_v1/tokenbf_v1 reasoning; applies unchanged here.
    INDEX idx_log_body_ngram assumeNotNull(body_value) TYPE ngrambf_v1(3, 4096, 2, 0) GRANULARITY 4,
    INDEX idx_log_attributes_tokenbf assumeNotNull(attributes_json) TYPE tokenbf_v1(8192, 3, 0) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (time_unix_nano, resource_id);
-- Schema 2.13.0 (decision on the keyset tiebreak index, list-pages-server-side plan phase 2):
-- the other four providers add an explicit (time_unix_nano DESC, id DESC) index for
-- GetLogPageAsync's keyset paging. No equivalent is added here: this table's own ORDER BY
-- already begins with time_unix_nano, so `ORDER BY time_unix_nano DESC, id DESC LIMIT n`
-- reads the MergeTree's sorted parts back-to-front (ClickHouse's read-in-order optimization
-- applies to a prefix of the sorting key in either direction) and only needs an in-memory
-- sort for ties within the same time_unix_nano -- and `id` here is
-- Keryhe.Telemetry.ClickHouse's monotonic per-process RowId generator, not a value ingestion
-- can duplicate across a batch, so same-nanosecond ties are effectively never contested. No
-- secondary index/projection was added; revisit with `EXPLAIN` if a live workload shows
-- otherwise.

-- =============================================================================
-- ALERTING
-- =============================================================================

CREATE TABLE IF NOT EXISTS alert_rules
(
    id               Int32,
    tenant_id        Int64,
    name             String,
    type             String,
    service_name     Nullable(String),
    condition_json   String,
    webhook_url      String,
    cooldown_minutes Int32 DEFAULT 60,
    enabled          UInt8 DEFAULT 1,
    created_at       DateTime64(9) DEFAULT now64(9),
    last_fired_at    Nullable(DateTime64(9))
)
ENGINE = ReplacingMergeTree
ORDER BY id;

CREATE TABLE IF NOT EXISTS alert_events
(
    id           Int64,
    rule_id      Int32,
    fired_at     DateTime64(9) DEFAULT now64(9),
    details_json String
)
ENGINE = MergeTree
ORDER BY (rule_id, id);

-- =============================================================================
-- RETENTION
-- =============================================================================

-- Single global row (id always 1) — see IRetentionSettingsRepository for why this is
-- untenanted. ReplacingMergeTree so ClickHouseRetentionSettingsRepository's
-- ALTER TABLE ... UPDATE mutation (see its "control-plane is best-effort" notes, same
-- pattern as alert_rules) collapses to one row at merge time, matching the alert_rules
-- dedup strategy.
CREATE TABLE IF NOT EXISTS retention_settings
(
    id                    Int8 DEFAULT 1,
    trace_retention_days  Int32,
    log_retention_days    Int32,
    metric_retention_days Int32,
    updated_at            DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree
ORDER BY id;

-- =============================================================================
-- ROLLUPS (schema 2.13.0, list-pages-server-side plan decisions 37-38)
-- =============================================================================

-- One row per signal + granularity. ClickHouse leases are best-effort (no atomic
-- read-check-update like the relational providers' UPDATE ... WHERE lease_expires_at < now --
-- see the alert-rule CRUD "control-plane is best-effort" notes for the same pattern), so two
-- API instances can briefly both believe they hold the lease; ReplacingMergeTree on the
-- summary tables below is what makes a double-rolled minute harmless.
CREATE TABLE IF NOT EXISTS rollup_state
(
    signal_name                   String,
    granularity              String,
    coverage_start_unix_nano Nullable(Int64),
    rolled_until_unix_nano   Int64 DEFAULT 0,
    repassed_until_unix_nano Int64 DEFAULT 0,
    lease_owner              Nullable(String),
    lease_expires_at         DateTime64(9) DEFAULT toDateTime64(0, 9)
)
ENGINE = ReplacingMergeTree
ORDER BY (signal_name, granularity);

-- Per-minute log summary, recomputed from raw log_records by RollupWorker -- never
-- incremented during ingestion (decision 38). Severity groups match
-- LogReadRepositoryBase.GetLogHistogramAsync's six-group CASE exactly.
-- ReplacingMergeTree(rolled_at): a minute rolled twice (by two API instances, since the lease
-- above is best-effort) collapses to the newest row at merge time; reads use FINAL, cheap on
-- tables this small.
CREATE TABLE IF NOT EXISTS log_rollup_minute
(
    bucket_unix_nano Int64,
    resource_id      Int64,
    trace_count      Int32 DEFAULT 0,
    debug_count      Int32 DEFAULT 0,
    info_count       Int32 DEFAULT 0,
    warn_count       Int32 DEFAULT 0,
    error_count      Int32 DEFAULT 0,
    fatal_count      Int32 DEFAULT 0,
    rolled_at        DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree(rolled_at)
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(bucket_unix_nano))
ORDER BY (bucket_unix_nano, resource_id);

-- Same shape, one row per hour.
CREATE TABLE IF NOT EXISTS log_rollup_hour
(
    bucket_unix_nano Int64,
    resource_id      Int64,
    trace_count      Int32 DEFAULT 0,
    debug_count      Int32 DEFAULT 0,
    info_count       Int32 DEFAULT 0,
    warn_count       Int32 DEFAULT 0,
    error_count      Int32 DEFAULT 0,
    fatal_count      Int32 DEFAULT 0,
    rolled_at        DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree(rolled_at)
ORDER BY (bucket_unix_nano, resource_id);

-- Traces whose root span never arrived (schema 2.13.1, decision 41): one row per trace,
-- holding the anchor span (its earliest span, whose own parent does not exist anywhere) that
-- the rollup worker detected per finished minute. ReplacingMergeTree(detected_at) keyed on
-- trace_id so a minute re-rolled by two racing API instances collapses to the newest row; the
-- rollup worker also issues an explicit lightweight DELETE for a trace whose root subsequently
-- arrives (same lightweight-DELETE precedent as the retention sweeps' `DELETE FROM spans`).
CREATE TABLE IF NOT EXISTS orphan_roots
(
    trace_id             String,
    span_id              String,
    resource_id          Int64,
    start_time_unix_nano Int64,
    end_time_unix_nano   Int64,
    detected_at          DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree(detected_at)
ORDER BY trace_id;

-- Per-minute trace summary (schema 2.13.1, decisions 37-38, 41): one row per minute, per
-- anchor span's resource, operation name (folded to '__other__' past the 200-distinct-name
-- cardinality guard) and inbound flag (anchor kind SERVER/CONSUMER). Counts traces whose
-- ANCHOR (null-parent root, or its orphan_roots span) starts in that minute; error flag and
-- duration are aggregated over the trace's full span set. lb_00..lb_39 are the fixed
-- latency-bucket counts (LatencyBucketSql) as plain columns so SQL can sum them across rows.
CREATE TABLE IF NOT EXISTS trace_rollup_minute
(
    bucket_unix_nano Int64,
    resource_id      Int64,
    root_name        String,
    inbound          UInt8,
    trace_count      Int32 DEFAULT 0,
    error_count      Int32 DEFAULT 0,
    duration_sum_ms  Float64 DEFAULT 0,
    duration_max_ms  Float64 DEFAULT 0,
    lb_00 Int32 DEFAULT 0,
    lb_01 Int32 DEFAULT 0,
    lb_02 Int32 DEFAULT 0,
    lb_03 Int32 DEFAULT 0,
    lb_04 Int32 DEFAULT 0,
    lb_05 Int32 DEFAULT 0,
    lb_06 Int32 DEFAULT 0,
    lb_07 Int32 DEFAULT 0,
    lb_08 Int32 DEFAULT 0,
    lb_09 Int32 DEFAULT 0,
    lb_10 Int32 DEFAULT 0,
    lb_11 Int32 DEFAULT 0,
    lb_12 Int32 DEFAULT 0,
    lb_13 Int32 DEFAULT 0,
    lb_14 Int32 DEFAULT 0,
    lb_15 Int32 DEFAULT 0,
    lb_16 Int32 DEFAULT 0,
    lb_17 Int32 DEFAULT 0,
    lb_18 Int32 DEFAULT 0,
    lb_19 Int32 DEFAULT 0,
    lb_20 Int32 DEFAULT 0,
    lb_21 Int32 DEFAULT 0,
    lb_22 Int32 DEFAULT 0,
    lb_23 Int32 DEFAULT 0,
    lb_24 Int32 DEFAULT 0,
    lb_25 Int32 DEFAULT 0,
    lb_26 Int32 DEFAULT 0,
    lb_27 Int32 DEFAULT 0,
    lb_28 Int32 DEFAULT 0,
    lb_29 Int32 DEFAULT 0,
    lb_30 Int32 DEFAULT 0,
    lb_31 Int32 DEFAULT 0,
    lb_32 Int32 DEFAULT 0,
    lb_33 Int32 DEFAULT 0,
    lb_34 Int32 DEFAULT 0,
    lb_35 Int32 DEFAULT 0,
    lb_36 Int32 DEFAULT 0,
    lb_37 Int32 DEFAULT 0,
    lb_38 Int32 DEFAULT 0,
    lb_39 Int32 DEFAULT 0,
    rolled_at        DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree(rolled_at)
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(bucket_unix_nano))
ORDER BY (bucket_unix_nano, resource_id, root_name, inbound);

-- Same shape, one row per hour.
CREATE TABLE IF NOT EXISTS trace_rollup_hour
(
    bucket_unix_nano Int64,
    resource_id      Int64,
    root_name        String,
    inbound          UInt8,
    trace_count      Int32 DEFAULT 0,
    error_count      Int32 DEFAULT 0,
    duration_sum_ms  Float64 DEFAULT 0,
    duration_max_ms  Float64 DEFAULT 0,
    lb_00 Int32 DEFAULT 0,
    lb_01 Int32 DEFAULT 0,
    lb_02 Int32 DEFAULT 0,
    lb_03 Int32 DEFAULT 0,
    lb_04 Int32 DEFAULT 0,
    lb_05 Int32 DEFAULT 0,
    lb_06 Int32 DEFAULT 0,
    lb_07 Int32 DEFAULT 0,
    lb_08 Int32 DEFAULT 0,
    lb_09 Int32 DEFAULT 0,
    lb_10 Int32 DEFAULT 0,
    lb_11 Int32 DEFAULT 0,
    lb_12 Int32 DEFAULT 0,
    lb_13 Int32 DEFAULT 0,
    lb_14 Int32 DEFAULT 0,
    lb_15 Int32 DEFAULT 0,
    lb_16 Int32 DEFAULT 0,
    lb_17 Int32 DEFAULT 0,
    lb_18 Int32 DEFAULT 0,
    lb_19 Int32 DEFAULT 0,
    lb_20 Int32 DEFAULT 0,
    lb_21 Int32 DEFAULT 0,
    lb_22 Int32 DEFAULT 0,
    lb_23 Int32 DEFAULT 0,
    lb_24 Int32 DEFAULT 0,
    lb_25 Int32 DEFAULT 0,
    lb_26 Int32 DEFAULT 0,
    lb_27 Int32 DEFAULT 0,
    lb_28 Int32 DEFAULT 0,
    lb_29 Int32 DEFAULT 0,
    lb_30 Int32 DEFAULT 0,
    lb_31 Int32 DEFAULT 0,
    lb_32 Int32 DEFAULT 0,
    lb_33 Int32 DEFAULT 0,
    lb_34 Int32 DEFAULT 0,
    lb_35 Int32 DEFAULT 0,
    lb_36 Int32 DEFAULT 0,
    lb_37 Int32 DEFAULT 0,
    lb_38 Int32 DEFAULT 0,
    lb_39 Int32 DEFAULT 0,
    rolled_at        DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree(rolled_at)
ORDER BY (bucket_unix_nano, resource_id, root_name, inbound);

INSERT INTO rollup_state (signal_name, granularity) VALUES ('logs', 'minute'), ('logs', 'hour'), ('traces', 'minute'), ('traces', 'hour');

-- =============================================================================
-- UTILITY
-- =============================================================================

CREATE TABLE IF NOT EXISTS schema_version
(
    version    String,
    applied_at DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree
ORDER BY version;
-- NOTE: the schema_version row is seeded at the very END of this script (after all
-- tables and views), so a partial/failed apply never records a version that the
-- apply-schema.sh version gate would wrongly treat as "already applied".

-- =============================================================================
-- VIEWS (parity with the relational providers; not on the hot read path — the
-- read repositories build their own SQL and extract service.name in C#).
-- JSON access uses ClickHouse's JSONExtractString.
-- =============================================================================

CREATE VIEW IF NOT EXISTS trace_summary AS
SELECT
    s.trace_id                                              AS trace_id_hex,
    s.trace_id                                              AS trace_id,
    count()                                                 AS span_count,
    min(s.start_time_unix_nano)                             AS trace_start_time,
    max(s.end_time_unix_nano)                               AS trace_end_time,
    max(s.end_time_unix_nano) - min(s.start_time_unix_nano) AS trace_duration_ns,
    any(r.id)                                               AS resource_id
FROM spans s
INNER JOIN resources r ON s.resource_id = r.id
GROUP BY s.trace_id;

CREATE VIEW IF NOT EXISTS service_map AS
SELECT
    parent_res.service_name AS parent_service,
    child_res.service_name AS child_service,
    child.kind                                                                   AS span_kind,
    count()                                                                      AS call_count
FROM spans child
INNER JOIN spans parent
    ON child.parent_span_id = parent.span_id AND child.trace_id = parent.trace_id
INNER JOIN resources parent_res ON parent.resource_id = parent_res.id
INNER JOIN resources child_res  ON child.resource_id  = child_res.id
WHERE parent_service != '' AND child_service != '' AND parent_service != child_service
GROUP BY parent_service, child_service, child.kind;

CREATE VIEW IF NOT EXISTS service_map_detailed AS
SELECT
    parent_res.service_name AS parent_service,
    child_res.service_name AS child_service,
    child.kind                                                                   AS span_kind,
    count()                                                                      AS call_count,
    avg(child.end_time_unix_nano - child.start_time_unix_nano) / 1000000         AS avg_duration_ms,
    min(child.end_time_unix_nano - child.start_time_unix_nano) / 1000000         AS min_duration_ms,
    max(child.end_time_unix_nano - child.start_time_unix_nano) / 1000000         AS max_duration_ms,
    countIf(child.status_code = 'ERROR')                                         AS error_count,
    (countIf(child.status_code = 'ERROR') / count()) * 100                       AS error_rate
FROM spans child
INNER JOIN spans parent
    ON child.parent_span_id = parent.span_id AND child.trace_id = parent.trace_id
INNER JOIN resources parent_res ON parent.resource_id = parent_res.id
INNER JOIN resources child_res  ON child.resource_id  = child_res.id
WHERE parent_service != '' AND child_service != '' AND parent_service != child_service
GROUP BY parent_service, child_service, child.kind;

CREATE VIEW IF NOT EXISTS log_severity_stats AS
SELECT
    severity_text,
    severity_number,
    count()                                              AS count,
    toDate(fromUnixTimestamp64Nano(time_unix_nano))      AS log_date
FROM log_records
WHERE time_unix_nano > 0
GROUP BY severity_text, severity_number, log_date;

-- Seeded with today's implicit defaults (traces 90d, logs 90d, metrics 180d).
INSERT INTO retention_settings (id, trace_retention_days, log_retention_days, metric_retention_days)
VALUES (1, 90, 90, 180);

-- =============================================================================
-- SCHEMA VERSION (recorded LAST)
-- =============================================================================
-- Only inserted when every statement above succeeded, so a partial apply cannot
-- leave a false version marker for the apply-schema.sh gate.
-- 2.13.1 adds orphan_roots/trace_rollup_minute/trace_rollup_hour (decisions 37-38, 41) and no
-- idx_spans_root_time equivalent -- see the comment on the spans table above for why. spans
-- already carried created_at (unlike the other four providers, which gained it only when they
-- needed it) so nothing changes there.
-- 2.13.0 adds rollup_state/log_rollup_minute/log_rollup_hour (decisions 37-38) and needs no
-- change to log_records' own ORDER BY -- see the comment on that table above for why the new
-- keyset tiebreak index the other four providers add is unnecessary here.
-- 2.12.0 is a no-op bump for ClickHouse alone, like 2.8.0 before it: the other four providers add
-- idx_spans_error (a status_code-filtered index) for mode=errors, but spans' ORDER BY (trace_id,
-- span_id) with a daily partition already gives ClickHouse the equivalent skip behavior — see the
-- comment on the spans table above.
-- 2.11.0 drops span_events and span_links, folding both into spans.events_json/links_json --
-- which also removes the retried-flush double-insert risk those two MergeTree tables carried,
-- since there is nothing left to insert alongside the ReplacingMergeTree-deduped spans row.
-- 2.10.0 adds retention_settings, backing the application-level RetentionWorker
-- (Keryhe.Telemetry.Api) that is now the one retention mechanism across all five providers.
-- 2.9.0 changes the metric data-point tables here exactly as it does everywhere else:
-- exemplar_id out, exemplars_json in. 2.8.0 before it was a no-op bump for ClickHouse alone --
-- spans' ORDER BY (trace_id, span_id) with a daily partition already gave it what the relational
-- providers got from the four indexes they dropped (see PostgreSQL-Schema.sql), and it has no
-- GIN-style JSONB index to carry the equivalent write cost of.
INSERT INTO schema_version (version) VALUES ('2.13.3');
