-- OpenTelemetry ClickHouse Schema
-- Supports OTLP logs, metrics, and traces as defined in opentelemetry-proto.
--
-- Produces the SAME LOGICAL table/column set as PostgreSQL-Schema.sql, adapted to
-- ClickHouse's columnar/OLAP model. The important differences from the relational
-- providers:
--
--   1. No auto-increment / RETURNING. Surrogate `id` columns are Int64 values
--      GENERATED BY THE APPLICATION (see Keryhe.Telemetry.ClickHouse):
--        - resources.id / instrumentation_scopes.id are derived deterministically from
--          the SHA-256 resource_hash/scope_hash, so re-inserts are idempotent.
--        - spans.id is derived deterministically from (trace_id, span_id).
--        - metrics.id, span_events.id, span_links.id use a monotonic in-process generator.
--   2. No UNIQUE constraints / ON CONFLICT. Dedup of resources, scopes, and spans is
--      handled by ReplacingMergeTree (collapses rows sharing the ORDER BY key at merge
--      time), backed by an in-process cache + per-batch dedup on the write side.
--   3. No foreign keys / cascades. Referential integrity is a write-path convention;
--      deletes remove child rows explicitly (see ClickHouseWriteStore).
--   4. Attributes are stored as String (JSON text) columns named *_json, matching how the
--      shared Dapper read repositories deserialize them in C#.
--   5. Timestamps *_unix_nano are Int64 (nanoseconds since epoch), as elsewhere.
--
-- Usage:
--   clickhouse-client --database telemetry --multiquery < ClickHouse-Schema.sql
--   (or:  schema/apply-schema.sh clickhouse telemetry)

-- =============================================================================
-- COMMON / MULTI-TENANT TABLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS tenants
(
    id         Int64,
    name       String,
    created_at DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree
ORDER BY id;

CREATE TABLE IF NOT EXISTS api_keys
(
    id           Int64,
    tenant_id    Int64,
    key_hash     String,
    name         String,
    is_active    UInt8 DEFAULT 1,
    created_at   DateTime64(9) DEFAULT now64(9),
    last_used_at Nullable(DateTime64(9))
)
ENGINE = ReplacingMergeTree
ORDER BY key_hash;

-- Resource: the entity producing telemetry. id = deterministic hash of resource_hash.
CREATE TABLE IF NOT EXISTS resources
(
    id              Int64,
    tenant_id       Int64,
    resource_hash   String,
    schema_url      Nullable(String),
    created_at      DateTime64(9) DEFAULT now64(9),
    attributes_json Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY (tenant_id, resource_hash);

-- Instrumentation scope (library). id = deterministic hash of scope_hash.
CREATE TABLE IF NOT EXISTS instrumentation_scopes
(
    id              Int64,
    name            String,
    version         Nullable(String),
    schema_url      Nullable(String),
    scope_hash      String,
    created_at      DateTime64(9) DEFAULT now64(9),
    attributes_json Nullable(String)
)
ENGINE = ReplacingMergeTree
ORDER BY scope_hash;

-- =============================================================================
-- TRACES
-- =============================================================================

-- Spans. Dedup key is (trace_id, span_id); id is derived from that pair.
CREATE TABLE IF NOT EXISTS spans
(
    id                       Int64,
    trace_id                 String,
    span_id                  String,
    parent_span_id           Nullable(String),
    resource_id              Int64,
    scope_id                 Int64,
    name                     String,
    kind                     String DEFAULT 'UNSPECIFIED',
    start_time_unix_nano     Int64,
    end_time_unix_nano       Int64,
    dropped_attributes_count Int32 DEFAULT 0,
    dropped_events_count     Int32 DEFAULT 0,
    dropped_links_count      Int32 DEFAULT 0,
    trace_state              Nullable(String),
    flags                    Int32 DEFAULT 0,
    status_code              String DEFAULT 'UNSET',
    status_message           Nullable(String),
    created_at               DateTime64(9) DEFAULT now64(9),
    attributes_json          Nullable(String)
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(start_time_unix_nano))
ORDER BY (trace_id, span_id);

CREATE TABLE IF NOT EXISTS span_events
(
    id                       Int64,
    span_id                  Int64,
    name                     String,
    time_unix_nano           Int64,
    dropped_attributes_count Int32 DEFAULT 0,
    attributes_json          Nullable(String)
)
ENGINE = MergeTree
ORDER BY (span_id, id);

CREATE TABLE IF NOT EXISTS span_links
(
    id                       Int64,
    span_id                  Int64,
    linked_trace_id          String,
    linked_span_id           String,
    trace_state              Nullable(String),
    flags                    Int32 DEFAULT 0,
    dropped_attributes_count Int32 DEFAULT 0,
    attributes_json          Nullable(String)
)
ENGINE = MergeTree
ORDER BY (span_id, id);

-- =============================================================================
-- METRICS
-- =============================================================================

CREATE TABLE IF NOT EXISTS metrics
(
    id          Int64,
    resource_id Int64,
    scope_id    Int64,
    name        String,
    description Nullable(String),
    unit        Nullable(String),
    type        String,
    created_at  DateTime64(9) DEFAULT now64(9)
)
ENGINE = MergeTree
ORDER BY (name, id);

CREATE TABLE IF NOT EXISTS gauge_data_points
(
    id                   Int64 DEFAULT 0,
    metric_id            Int64,
    start_time_unix_nano Nullable(Int64),
    time_unix_nano       Int64,
    value_double         Nullable(Float64),
    value_int            Nullable(Int64),
    flags                Int32 DEFAULT 0,
    exemplar_id          Nullable(Int64),
    attributes_json      Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS sum_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    value_double            Nullable(Float64),
    value_int               Nullable(Int64),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    is_monotonic            UInt8 DEFAULT 0,
    flags                   Int32 DEFAULT 0,
    exemplar_id             Nullable(Int64),
    attributes_json         Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS histogram_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    count                   Int64,
    sum_value               Nullable(Float64),
    bucket_counts           Nullable(String),
    explicit_bounds         Nullable(String),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    flags                   Int32 DEFAULT 0,
    min_value               Nullable(Float64),
    max_value               Nullable(Float64),
    exemplar_id             Nullable(Int64),
    attributes_json         Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS exponential_histogram_data_points
(
    id                      Int64 DEFAULT 0,
    metric_id               Int64,
    start_time_unix_nano    Nullable(Int64),
    time_unix_nano          Int64,
    count                   Int64,
    sum_value               Nullable(Float64),
    scale                   Int32,
    zero_count              Int64,
    positive_offset         Nullable(Int32),
    positive_bucket_counts  Nullable(String),
    negative_offset         Nullable(Int32),
    negative_bucket_counts  Nullable(String),
    aggregation_temporality String DEFAULT 'UNSPECIFIED',
    flags                   Int32 DEFAULT 0,
    min_value               Nullable(Float64),
    max_value               Nullable(Float64),
    exemplar_id             Nullable(Int64),
    attributes_json         Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS summary_data_points
(
    id                   Int64 DEFAULT 0,
    metric_id            Int64,
    start_time_unix_nano Nullable(Int64),
    time_unix_nano       Int64,
    count                Int64,
    sum_value            Float64,
    quantile_values      Nullable(String),
    flags                Int32 DEFAULT 0,
    attributes_json      Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (metric_id, time_unix_nano);

CREATE TABLE IF NOT EXISTS exemplars
(
    id                  Int64 DEFAULT 0,
    filtered_attributes Nullable(String),
    time_unix_nano      Int64,
    value_double        Nullable(Float64),
    value_int           Nullable(Int64),
    span_id             Nullable(String),
    trace_id            Nullable(String)
)
ENGINE = MergeTree
ORDER BY time_unix_nano;

-- =============================================================================
-- LOGS
-- =============================================================================

CREATE TABLE IF NOT EXISTS log_records
(
    id                       Int64 DEFAULT 0,
    resource_id              Int64,
    scope_id                 Int64,
    time_unix_nano           Int64 DEFAULT 0,
    observed_time_unix_nano  Nullable(Int64),
    severity_number          Nullable(Int32),
    severity_text            Nullable(String),
    event_name               Nullable(String),
    body_type                Nullable(String),
    body_value               Nullable(String),
    dropped_attributes_count Int32 DEFAULT 0,
    flags                    Int32 DEFAULT 0,
    trace_id                 Nullable(String),
    span_id                  Nullable(String),
    created_at               DateTime64(9) DEFAULT now64(9),
    attributes_json          Nullable(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(fromUnixTimestamp64Nano(time_unix_nano))
ORDER BY (time_unix_nano, resource_id);

-- =============================================================================
-- ALERTING
-- =============================================================================

CREATE TABLE IF NOT EXISTS alert_rules
(
    id               Int32,
    tenant_id        Int64,
    name             String,
    type             String,
    service_name     Nullable(String),
    condition_json   String,
    webhook_url      String,
    cooldown_minutes Int32 DEFAULT 60,
    enabled          UInt8 DEFAULT 1,
    created_at       DateTime64(9) DEFAULT now64(9),
    last_fired_at    Nullable(DateTime64(9))
)
ENGINE = ReplacingMergeTree
ORDER BY id;

CREATE TABLE IF NOT EXISTS alert_events
(
    id           Int64,
    rule_id      Int32,
    fired_at     DateTime64(9) DEFAULT now64(9),
    details_json String
)
ENGINE = MergeTree
ORDER BY (rule_id, id);

-- =============================================================================
-- UTILITY
-- =============================================================================

CREATE TABLE IF NOT EXISTS schema_version
(
    version    String,
    applied_at DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree
ORDER BY version;
-- NOTE: the schema_version row is seeded at the very END of this script (after all
-- tables and views), so a partial/failed apply never records a version that the
-- apply-schema.sh version gate would wrongly treat as "already applied".

-- =============================================================================
-- VIEWS (parity with the relational providers; not on the hot read path — the
-- read repositories build their own SQL and extract service.name in C#).
-- JSON access uses ClickHouse's JSONExtractString.
-- =============================================================================

CREATE VIEW IF NOT EXISTS trace_summary AS
SELECT
    s.trace_id                                              AS trace_id_hex,
    s.trace_id                                              AS trace_id,
    count()                                                 AS span_count,
    min(s.start_time_unix_nano)                             AS trace_start_time,
    max(s.end_time_unix_nano)                               AS trace_end_time,
    max(s.end_time_unix_nano) - min(s.start_time_unix_nano) AS trace_duration_ns,
    any(r.id)                                               AS resource_id
FROM spans s
INNER JOIN resources r ON s.resource_id = r.id
GROUP BY s.trace_id;

CREATE VIEW IF NOT EXISTS service_map AS
SELECT
    JSONExtractString(assumeNotNull(parent_res.attributes_json), 'service.name') AS parent_service,
    JSONExtractString(assumeNotNull(child_res.attributes_json),  'service.name') AS child_service,
    child.kind                                                                   AS span_kind,
    count()                                                                      AS call_count
FROM spans child
INNER JOIN spans parent
    ON child.parent_span_id = parent.span_id AND child.trace_id = parent.trace_id
INNER JOIN resources parent_res ON parent.resource_id = parent_res.id
INNER JOIN resources child_res  ON child.resource_id  = child_res.id
WHERE parent_service != '' AND child_service != '' AND parent_service != child_service
GROUP BY parent_service, child_service, child.kind;

CREATE VIEW IF NOT EXISTS service_map_detailed AS
SELECT
    JSONExtractString(assumeNotNull(parent_res.attributes_json), 'service.name') AS parent_service,
    JSONExtractString(assumeNotNull(child_res.attributes_json),  'service.name') AS child_service,
    child.kind                                                                   AS span_kind,
    count()                                                                      AS call_count,
    avg(child.end_time_unix_nano - child.start_time_unix_nano) / 1000000         AS avg_duration_ms,
    min(child.end_time_unix_nano - child.start_time_unix_nano) / 1000000         AS min_duration_ms,
    max(child.end_time_unix_nano - child.start_time_unix_nano) / 1000000         AS max_duration_ms,
    countIf(child.status_code = 'ERROR')                                         AS error_count,
    (countIf(child.status_code = 'ERROR') / count()) * 100                       AS error_rate
FROM spans child
INNER JOIN spans parent
    ON child.parent_span_id = parent.span_id AND child.trace_id = parent.trace_id
INNER JOIN resources parent_res ON parent.resource_id = parent_res.id
INNER JOIN resources child_res  ON child.resource_id  = child_res.id
WHERE parent_service != '' AND child_service != '' AND parent_service != child_service
GROUP BY parent_service, child_service, child.kind;

CREATE VIEW IF NOT EXISTS log_severity_stats AS
SELECT
    severity_text,
    severity_number,
    count()                                              AS count,
    toDate(fromUnixTimestamp64Nano(time_unix_nano))      AS log_date
FROM log_records
WHERE time_unix_nano > 0
GROUP BY severity_text, severity_number, log_date;

-- =============================================================================
-- SCHEMA VERSION (recorded LAST)
-- =============================================================================
-- Only inserted when every statement above succeeded, so a partial apply cannot
-- leave a false version marker for the apply-schema.sh gate.
INSERT INTO schema_version (version) VALUES ('2.6.0');
