import { Component, ElementRef, HostListener, computed, inject, signal } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatNativeDateModule } from '@angular/material/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { FormsModule } from '@angular/forms';
import { TimePreset, TimeRangeService } from '../../../core/services/time-range.service';

@Component({
  selector: 'app-time-range-picker',
  standalone: true,
  imports: [
    MatIconModule, MatButtonModule, MatDatepickerModule,
    MatFormFieldModule, MatInputModule, MatNativeDateModule, FormsModule,
  ],
  template: `
    <div class="picker-wrap">
      <button mat-stroked-button class="trigger" (click)="togglePanel($event)">
        <mat-icon class="trigger-icon">schedule</mat-icon>
        <span class="trigger-label">{{ selectionLabel() }}</span>
        <mat-icon class="trigger-caret">{{ showPanel() ? 'arrow_drop_up' : 'arrow_drop_down' }}</mat-icon>
      </button>

      @if (showPanel()) {
        <div class="panel" (click)="$event.stopPropagation()">
          <div class="preset-list">
            @for (p of presets; track p.value) {
              <button mat-button class="preset-item"
                      [class.active]="timeRange.range().preset === p.value"
                      (click)="onPreset(p.value)">
                {{ p.label }}
              </button>
            }
          </div>

          <div class="custom-divider">Custom range</div>

          <div class="custom-row">
            <span class="custom-label">From</span>
            <mat-form-field appearance="outline" subscriptSizing="dynamic">
              <input matInput [matDatepicker]="startPicker" [(ngModel)]="customStart" placeholder="Date">
              <mat-datepicker-toggle matIconSuffix [for]="startPicker" />
              <mat-datepicker #startPicker />
            </mat-form-field>
            <input class="time-input" type="time" [value]="toTimeString(customStart)"
                   (change)="onTimeChange('start', $event)" />
          </div>
          <div class="custom-row">
            <span class="custom-label">To</span>
            <mat-form-field appearance="outline" subscriptSizing="dynamic">
              <input matInput [matDatepicker]="endPicker" [(ngModel)]="customEnd" placeholder="Date">
              <mat-datepicker-toggle matIconSuffix [for]="endPicker" />
              <mat-datepicker #endPicker />
            </mat-form-field>
            <input class="time-input" type="time" [value]="toTimeString(customEnd)"
                   (change)="onTimeChange('end', $event)" />
          </div>
          <div class="custom-actions">
            <button mat-button (click)="closePanel()">Cancel</button>
            <button mat-flat-button (click)="applyCustom()" [disabled]="!customStart || !customEnd">Apply</button>
          </div>
        </div>
      }
    </div>
  `,
  styles: [`
    /* min-width: 0 on the host and .picker-wrap turns this component into a genuinely shrinkable
       flex item inside the shell's .toolbar-controls-secondary, instead of one that's held at its
       content's natural width — a flex item's default min-width is auto (= content size), which
       would otherwise block .trigger-label from ever truncating below. */
    :host { min-width: 0; }
    .picker-wrap { position: relative; display: flex; min-width: 0; }

    .trigger {
      height: 36px;
      display: inline-flex;
      align-items: center;
      gap: 4px;
      flex: 1 1 auto;
      min-width: 0;
    }
    // mat-stroked-button wraps its projected text (our .trigger-label) in its own internal
    // <span class="mdc-button__label">, generated by MatButton's template rather than ours — so it
    // needs ::ng-deep to reach, and like every other link in this chain, its default min-width of
    // auto would otherwise stop .trigger-label from ever shrinking below its full content width.
    ::ng-deep .mdc-button__label {
      flex: 1 1 auto;
      min-width: 0;
      overflow: hidden;
    }
    .trigger-icon { font-size: 18px; width: 18px; height: 18px; flex: 0 0 auto; }
    /* Always shrinkable and ellipsis-truncating, at every width — not gated behind a viewport
       breakpoint. .trigger-label is the only part of the trigger allowed to give up space (the
       icon and caret stay flex: 0 0 auto above), so a too-long formatted range
       ("Jul 25 16:13 – Jul 25 16:33") degrades to an ellipsis exactly when the picker's actual
       allotted space runs out — whether that's a narrow viewport or a long tenant name eating
       into the row — and never before. The trigger's own padding/gap never change. */
    .trigger-label {
      font-size: 13px;
      // block (not the default inline) so it actually establishes a box to clip against — an
      // inline element's own overflow/text-overflow have no visual effect, even though its
      // ancestor's overflow: hidden alone will still hard-cut the text with no ellipsis.
      display: block;
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
    }
    .trigger-caret { font-size: 20px; width: 20px; height: 20px; margin-left: -2px; flex: 0 0 auto; }

    .panel {
      position: absolute;
      top: calc(100% + 4px);
      right: 0;
      z-index: 11;
      background: var(--mat-sys-surface-container-high);
      border: 1px solid var(--mat-sys-outline-variant);
      border-radius: 8px;
      padding: 8px;
      box-shadow: 0 4px 12px rgba(0,0,0,.15);
      display: flex;
      flex-direction: column;
      gap: 8px;
      min-width: 340px;
    }

    .preset-list {
      display: flex;
      flex-direction: column;
    }
    .preset-item {
      justify-content: flex-start;
      text-align: left;
      font-size: 13px;
    }
    .preset-item.active {
      background: var(--mat-sys-secondary-container);
      color: var(--mat-sys-on-secondary-container);
    }

    .custom-divider {
      font-size: 12px;
      font-weight: 500;
      color: var(--mat-sys-on-surface-variant);
      padding: 4px 8px 0;
      border-top: 1px solid var(--mat-sys-outline-variant);
      margin-top: 4px;
      padding-top: 8px;
    }

    .custom-row {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 0 4px;
    }

    .custom-label {
      width: 28px;
      font-size: 12px;
      color: var(--mat-sys-on-surface-variant);
    }

    .time-input {
      width: 80px;
      height: 36px;
      border: 1px solid var(--mat-sys-outline);
      border-radius: 4px;
      padding: 0 6px;
      font-size: 13px;
      background: transparent;
      color: var(--mat-sys-on-surface);
    }

    .custom-actions {
      display: flex;
      justify-content: flex-end;
      gap: 8px;
      margin-top: 4px;
    }
  `],
})
export class TimeRangePickerComponent {
  protected readonly timeRange = inject(TimeRangeService);
  private readonly elementRef = inject(ElementRef);
  private readonly snack = inject(MatSnackBar);

  protected readonly presets: { value: TimePreset; label: string }[] = [
    { value: '1h', label: 'Last 1 Hour' },
    { value: '3h', label: 'Last 3 Hours' },
    { value: '6h', label: 'Last 6 Hours' },
    { value: '12h', label: 'Last 12 Hours' },
    { value: '24h', label: 'Last 24 Hours' },
    { value: '3d', label: 'Last 3 Days' },
    { value: '7d', label: 'Last 7 Days' },
  ];

  protected readonly showPanel = signal(false);

  protected readonly selectionLabel = computed(() => {
    const range = this.timeRange.range();
    if (range.preset === 'custom') {
      return `${this.formatRangeBound(range.start)} – ${this.formatRangeBound(range.end)}`;
    }
    return this.timeRange.presetLabel(range.preset);
  });

  protected customStart: Date | null = null;
  protected customEnd: Date | null = null;

  protected togglePanel(event: Event): void {
    event.stopPropagation();
    if (!this.showPanel()) {
      const { start, end } = this.timeRange.range();
      this.customStart = new Date(start);
      this.customEnd = new Date(end);
    }
    this.showPanel.update(v => !v);
  }

  protected closePanel(): void {
    this.showPanel.set(false);
  }

  @HostListener('document:click', ['$event'])
  protected onDocumentClick(event: Event): void {
    if (!this.showPanel()) return;
    const target = event.target as HTMLElement;
    if (this.elementRef.nativeElement.contains(target)) return;
    if (target.closest('.cdk-overlay-container')) return;
    this.showPanel.set(false);
  }

  protected onPreset(value: TimePreset): void {
    this.timeRange.setPreset(value);
    this.showPanel.set(false);
  }

  protected toTimeString(d: Date | null): string {
    if (!this.isValidDate(d)) return '00:00';
    return d.toTimeString().slice(0, 5);
  }

  protected onTimeChange(which: 'start' | 'end', event: Event): void {
    const [h, m] = (event.target as HTMLInputElement).value.split(':').map(Number);
    const base = which === 'start' ? this.customStart : this.customEnd;
    if (!base) return;
    const d = new Date(base);
    d.setHours(h, m, 0, 0);
    if (which === 'start') this.customStart = d;
    else this.customEnd = d;
  }

  protected applyCustom(): void {
    if (!this.customStart || !this.customEnd) return;
    if (!this.isValidDate(this.customStart) || !this.isValidDate(this.customEnd)) {
      this.snack.open('Enter a valid start and end date/time.', undefined, { duration: 4000 });
      return;
    }
    if (this.customStart.getTime() >= this.customEnd.getTime()) {
      this.snack.open('End date/time must be after the start date/time.', undefined, { duration: 4000 });
      return;
    }
    this.showPanel.set(false);
    this.timeRange.setCustom(this.customStart, this.customEnd);
  }

  private isValidDate(d: Date | null): d is Date {
    return d instanceof Date && !isNaN(d.getTime());
  }

  private formatRangeBound(d: Date): string {
    const date = d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
    const time = d.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', hour12: false });
    return `${date} ${time}`;
  }
}
